json.id @post.id
json.image_url @post.image_url
json.owner @post.owner
json.user_id @post.user_id
json.answer @post.answer
json.hint @post.hint
json.solved @post.solved
json.solved_by @post.solved_by
json.created @post.created_at
json.updated @post.updated_at