json.post_id @post.id
json.owner @post.owner
json.url @post.image_url
json.answer @post.answer
json.hint @post.hint
json.solved @post.solved
json.solved_by @post.solved_by
json.attempts @post.attempts
json.times_solved @post.times_solved